config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'application#index'

  get 'login' => 'sessions#new'
  get 'signup' => 'users#new'

  post 'login' => 'sessions#create'
  post 'signup' => 'users#create'
  
  delete 'logout' => 'sessions#destroy'

  resources :users, only: [:show, :new, :create] do
    resources :goals, only: [:index, :show, :new, :create]
    resources :journeys
  end

  get "/auth/google_oauth2/callback", to: "sessions#google_login"

end

app/models/Journey.rb
class Journey < ActiveRecord::Base
    belongs_to :user
    belongs_to :goal

    validates_presence_of :title, :content, :goal

    scope :title_search, -> (user_id, query) {
        where("user_id=?", user_id).
        where("title LIKE ?", "%#{query}%")
    }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/goal.rb
class Goal < ActiveRecord::Base
    has_many :journeys
    has_many :users, through: :journeys

    validates :name, :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    validates :name, :password, presence: true
    validates :email, presence: true, uniqueness: true
    
    has_many :journeys
    has_many :goals, through: :journeys
end

app/controllers/Journeys_controller.rb
class JourneysController < ApplicationController
    before_action :require_login
    before_action :set_journey, only: [:show, :edit, :destroy]

    def index
        show_my_journeys if !correct_user_link
        @user = current_user
        @query = params[:query]

        if !@query.blank?
            @journeys = Journey.title_search(@user.id, @query)
        else
            @journeys = current_user.journeys
        end

    end
    
    def show
        if @journey && correct_user_link
            @goal = @journey.goal
        else
            show_my_journeys
        end
    end

    def new
        redirect_to new_user_journey_path(current_user) if !correct_user_link
        @journey = current_user.journeys.new
        @goals = Goal.all
    end

    def create
        @journey = current_user.journeys.create(journey_params)
        if @journey.save
            redirect_to user_journey_path(current_user, @journey)
        else
            @goals = Goal.all
            render :new
        end
    end
    
    def edit
        redirect_to edit_user_journey_path(current_user, @journey) if !correct_user_link
        @journey ? @goals = Goal.all : show_my_journeys
    end
    
    def update
        @journey = current_user.journeys.find_by(id: params[:id])
        if @journey.update(journey_params)
            redirect_to user_journey_path(current_user, @journey)
        else
            @goals = Goal.all
            render :edit
        end
    end

    def destroy
        @journey.destroy
        show_my_journeys
    end

    private

    def journey_params
        params.require(:journey).permit(:title, :content, :user_id, :goal_id)
    end

    def set_journey
        @journey = current_user.journeys.find_by(id: params[:id])
    end

    def show_my_journeys
        redirect_to user_journeys_path(current_user)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user

    def index;  end

    private
    
    def current_user
        @user = User.find_by(id: session[:user_id])
    end

    def require_login
        redirect_to root_path if !current_user
    end

    def redirect_if_logged_in
        redirect_to user_path(current_user) if current_user
    end

    def correct_user_link
        params[:user_id].to_i == current_user.id
    end

    def show_welcome_page
        redirect_to user_path(current_user)
    end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
    before_action :require_login

    def index
        if correct_user_link
            @user = current_user
            @goals = @user.goals
        else
            show_my_goals
        end
    end

    def show
        @goal = current_user.goals.find_by(id: params[:id])
        unless @goal && correct_user_link
            show_my_goals
        end
    end

    def new
        @goal = Goal.new
    end

    def create
        @goal = Goal.create(goal_params)
        if @goal.save
            redirect_to user_journeys_path(current_user), alert: "Your goal has been saved!"
        else
            render :new
        end
    end

    private
    
    def show_my_goals
        redirect_to user_goals_path(current_user)
    end

    def goal_params
        params.require(:goal).permit(:name, :description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :redirect_if_logged_in, only: [:new, :create]

    def new;  end

    def create
        @user = User.find_by(email: params[:user][:email])
        if @user && @user.authenticate(params[:user][:password])
            session[:user_id] = @user.id
            show_welcome_page
        else
            @errors = ["Please enter a valid email and password."]
            render :new
        end
    end

    def destroy
        session.clear
        redirect_to root_path
    end

    def google_login
        @user = User.find_or_create_by(email: auth_hash[:email]) do |u|
            u.password = SecureRandom.hex
            u.name = auth_hash[:first_name]
        end
        
        session[:user_id] = @user.id
        redirect_to user_path(current_user)
    end
    
    private
    
    def auth_hash
        request.env['omniauth.auth']['info']
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :redirect_if_logged_in, only: [:new, :create]
    before_action :require_login, except: [:new, :create]

    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)
        if @user.save
            session[:user_id] = @user.id
            show_welcome_page
        else
            render :new
        end
    end
    
    def show
        if params[:id].to_i == current_user.id
            @user = current_user
        else
            show_welcome_page
        end
    end

    private

    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_errors.erb
<% errors.each do |m| %>
  <li class="error"><%= m %></li>
<% end %>

app/views/application/index.erb
<header class="header">
    <h1 class="heading-primary">Social Media Distancing</h1>
    <h2 class="heading-secondary">A goal-setting app that that helps you focus on <em>yourself!</em></h2>
</header>

app/views/entries/_form.erb
<%= form_for ([@entry.user, @entry]) do |f| %>
    <%= f.label :title %><br>
    <%= f.text_field :title %><br><br>

    <%= f.label :content %><br>
    <%= f.text_area :content %><br><br>

    <%= f.label :goal %><br>

    <%= f.collection_select :goal_id, @goals, :id, :name,
        @entry.goal ? { selected: @entry.goal.id } : { include_blank: true } %><br><br>

    <%= f.submit %>
<% end %>

app/views/goals/index.erb
<div class="entries">
    <div class="entries__left">
        <h1 class="heading">My Goals</h1>
        <span><%= link_to 'New Goal', new_user_goal_path(current_user), class: "entry__new" %>&larrhk;</span>
    </div>
    <div class="entries__right">
        <ul class="entries__list">
        <% @goals.uniq.each do |goal| %>
            <li class="entries__item">
                <p class="entries__item--name"><%= goal.name %></p>
                <p class="entries__item--description"><%= goal.description %></p>
            </li>
        <% end %>
        </ul>
    </div>
</div>

app/views/goals/new.erb
<div class="new-entries">
    <h1 class="heading">New Goal</h1>
    <p><em>Goals will be available to all users to chose from.</em></p><br>
    <p><em>You can select your new goal on your <%= link_to "Journeys page", user_journeys_path(current_user) %>.</em></p>

    <%= form_with model: @goal, url: user_goals_url(current_user), class: 'new-entries__form', local: true do |f| %>
        <%= f.label :name %><br>
        <%= f.text_field :name %><br><br>

        <%= f.label :description %><br>
        <%= f.text_area :description %><br><br>

        <%= render partial: 'application/errors', locals: {errors: @goal.errors.full_messages} %>

        <%= f.submit %>
    <% end %>
</div>

app/views/goals/show.erb
<h1><%= @goal.name %></h1>
<p><%= @goal.description %></p>

# link is taken off but can still navigate to page by url

app/views/journeys/_form.erb
<%= form_with model: ([@journey.user, @journey]), class: 'new-entries__form', local: true do |f| %>
    <%= f.label :title %><br>
    <%= f.text_field :title %><br><br>

    <%= f.label :content %><br>
    <%= f.text_area :content %><br><br>

    <%= f.label :goal %><br>

    <%= f.collection_select :goal_id, @goals, :id, :name,
        @journey.goal ? { selected: @journey.goal.id } : { include_blank: true } %><br><br>

    <%= f.submit %>
<% end %>

app/views/journeys/edit.erb
<div class="new-entries">

    <h1 class="heading">Edit Journey</h1>

    <%= render partial: 'application/errors', locals: {errors: @journey.errors.full_messages} %>

    <%= render partial: 'form', locals: {url: user_journey_url(current_user, @journey) } %>
</div>

app/views/journeys/index.erb
<div class="entries">
    <div class="entries__left">
        <h1 class="heading">My Journeys</h1>
        <%= form_tag user_journeys_path(@user), class: 'entry__form', method: :get do %>
            <%= text_field_tag :query, @query, class: 'entry__searchbar' %>
            <%= submit_tag "Search",  id: 'entry__submit'%>
        <% end %><br>
        <span><%= link_to 'New Journey', new_user_journey_path(@user) %>&larrhk;</span>
    </div>
    <div class="entries__right">
        <div class="entries__list">
            <% if @journeys.empty? %>
                <p><em>No results found</p></em>
            <% else %>
                <ul class="entries__list">
                <% @journeys.each do |journey| %>
                    <li class="entries__item"><%= link_to journey.title, user_journey_path(@user, journey) %></li>
                <% end %>
                </ul>
            <% end %>
        </div>
    </div>
</div>

app/views/journeys/new.erb
<div class="new-entries">
        <h1 class="heading">New Journey</h1>
        <p><em>Can't find the goal you're looking for?</em></p>
        <p><em>Create one on your <%= link_to "Goals page", new_user_goal_path(current_user) %>.</em></p>
        <%= render partial: 'form', locals: {url: user_journeys_url(current_user) } %>

        <%= render partial: 'application/errors', locals: {errors: @journey.errors.full_messages} %>

</div>

app/views/journeys/show.erb
<div class="entry">
    <h1 class="heading"><%= @journey.title %></h1>

    <%= link_to "Edit Journey", edit_user_journey_path(@user, @journey) %><br><br>
    <text><%= @journey.content %></text>

    <h2 class="heading-small">Goal:</h2>

    <%= @goal.name %> - <%= @goal.description %>

    <%= button_to "Delete", user_journey_path(@journey), method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Social Media Distancing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Epilogue&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    
    <!-- the below meta tags will help add thubnails to linkedin features section -->
    <meta name="description" content="Social Media Distancing App" />
    <meta name="title" property="og:title" content="Social Media Distancing" />
    <meta property="og:type" content="Website" />
    <meta name="image" property="og:image" content="https://portfolio-b36dc.web.app/static/media/social_media_distancing.39ef21b5.png" />
    <meta name="description" property="og:description" content="Social Media Distancing App" />
    <meta name="author" content="Chindalath Traymany" />
  </head>

  <body>
    <div class="navigation__container">
      <nav class="navigation">
        <ul class="navigation__list">
          <% if !current_user %>
            <li class="navigation__item"><%= link_to "Home", root_path, class: 'navigation__link' %></li>
            <li class="navigation__item"><%= link_to "Sign Up", signup_path, class: 'navigation__link' %></li>
            <li class="navigation__item"><%= link_to "Log In", login_path, class: 'navigation__link' %></li>
            <%#li class="navigation__item"><%= link_to "Continue with Google", '/auth/google_oauth2', class: 'navigation__link' %></%li>
          <% else %>
            <li class="navigation__item"><%= link_to "Home", user_path(current_user), class: 'navigation__link' %></li>
            <li class="navigation__item"><%= link_to "Goals", user_goals_path(current_user), class: 'navigation__link' %></li>
            <li class="navigation__item"><%= link_to "Journeys", user_journeys_path(current_user), class: 'navigation__link' %></li>
            <li class="navigation__item"><%= button_to "Log Out", logout_path, class: 'navigation__link', id: 'logout__button', method: :delete %></li>
            <%# link_to was having issues (no route matches GET logout) %>
          <% end %>
        </ul>
      </nav>
    </div>
    
    <%= yield %>

  </body>

</html>

app/views/users/new.erb
<div class="session">
    <div class="session__content">
        <div class="session__left">
            &nbsp;
        </div>
        <div class="session__right">
            <h1 class="session__heading">Sign Up</h1>

            <%#render partial: "application/errors", locals: {errors: @user.errors.full_messages} %>

            <%= form_with model: @user, url: '/signup', local: true, class: 'signup__form' do |f| %>
                <%= f.label :name %><br>
                <%= f.text_field :name %><br><br>

                <%= f.label :email %><br>
                <%= f.text_field :email %><br><br>

                <%= f.label :password %><br>
                <%= f.password_field :password %><br><br>

                <%= f.label :confirm_password %><br>
                <%= f.password_field :password_confirmation %><br><br>

                <%= f.submit 'Sign Up' %>
            <% end %>
        </div>
    </div>
</div>

app/views/users/show.erb
<div class="welcome">
    <h1 class="heading-primary">Welcome, <%= @user.name %>!</h1>
    <h2 class="heading-secondary">Get started by creating a new goal or journey.</h2>
</div>